import { Inter } from 'next/font/google'
import Link from "next/link"
import './globals.css'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from "@/pages/api/auth/[...nextauth]"
import Profile from './ProfileGallery'
import LoginInfo from './LoginInfo'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Profile />
        <div className="navbar">
          <div className="left_nav">
            <Link href='/' className="logo">forum</Link>
          </div>
          <div className="center_nav">
            <Link href='/write'>Write</Link>
            <Link href='/list'>List</Link>
          </div>
          <div className="right_nav">
            {
              session === null ?
                <LoginBtn />
                :
                // <div className="user-info">
                //   <img src={session.user.img} className="profile-img" alt="" />
                //   <div className="welcome"><b>{session.user.name}</b>님 환영합니다!</div>
                //   <LogoutBtn />
                // </div>
                <LoginInfo />
            }
          </div>
          
        </div>
        {children}
      </body>
    </html>
  )
}

